default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: pretty-format-json
        args: ['--autofix']

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)
        args: ['--line-length=120']

  - repo: https://github.com/psf/black
    rev: "24.3.0"
    hooks:
      - id: black
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-docstrings
        - flake8-quotes
        - flake8-builtins
        - flake8-variables-names
        - pydocstyle
