# Generated by Django 5.1.15 on 2026-08-21 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0008_alter_description_alter_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('subdivision', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('working_days', models.PositiveSmallIntegerField(help_text='7-bit mask; bit 0=Mon … bit 6=Sun. E.g. Mon-Fri = 31.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_assignments', to='calendars.calendar')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_assignments', to='people.person')),
            ],
            options={
                'ordering': ['person_id', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='holiday_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='calendars.holidaycalendar'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='weekly_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='calendars.weeklypattern'),
        ),
    ]
