# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('people', '0009_alter_person_description_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='holiday_calendar',
            field=models.ForeignKey(help_text='Public-holiday source overlaid on top of the weekly pattern.', on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='calendars.holidaycalendar'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(help_text="Unique display name of the calendar (e.g. 'Poland Mon-Fri').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='weekly_pattern',
            field=models.ForeignKey(help_text='Recurring weekly working-day pattern used by this calendar.', on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='calendars.weeklypattern'),
        ),
        migrations.AlterField(
            model_name='calendarassignment',
            name='calendar',
            field=models.ForeignKey(help_text='Working calendar in effect during this window.', on_delete=django.db.models.deletion.PROTECT, related_name='person_assignments', to='calendars.calendar'),
        ),
        migrations.AlterField(
            model_name='calendarassignment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Inclusive last day of the assignment; NULL means the assignment is open-ended.', null=True),
        ),
        migrations.AlterField(
            model_name='calendarassignment',
            name='person',
            field=models.ForeignKey(help_text='Person the calendar is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_assignments', to='people.person'),
        ),
        migrations.AlterField(
            model_name='calendarassignment',
            name='start_date',
            field=models.DateField(help_text='Inclusive first day of the assignment.'),
        ),
        migrations.AlterField(
            model_name='holidaycalendar',
            name='country_code',
            field=models.CharField(help_text="ISO-3166 alpha-2 country code supported by python-holidays (e.g. 'PL', 'US').", max_length=2),
        ),
        migrations.AlterField(
            model_name='holidaycalendar',
            name='name',
            field=models.CharField(help_text="Unique display name of the holiday calendar (e.g. 'Poland PL').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='holidaycalendar',
            name='subdivision',
            field=models.CharField(blank=True, default='', help_text="Optional subdivision code (e.g. US state 'TX'); empty for country-wide holidays.", max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklypattern',
            name='name',
            field=models.CharField(help_text="Unique display name of the weekly pattern (e.g. 'Mon-Fri').", max_length=100, unique=True),
        ),
    ]
