# Generated by Django 5.1.15 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('contracts', '0001_initial'), ('contracts', '0002_rename_id_contract_identifier'), ('contracts', '0003_rename_identifier_contract_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
