# Generated by Django 5.1.15 on 2026-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial_squashed_0003_rename_identifier_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.IntegerField(help_text='Business-supplied contract identifier (integer, immutable).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(help_text='Display name of the contract (typically the contract reference).', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size',
            field=models.IntegerField(help_text='Contracted volume in whole units (semantics defined by the contract).'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(help_text="Free-form contract status label (e.g. 'active', 'closed', 'draft').", max_length=50),
        ),
    ]
