# Generated by Django 5.1.15 on 2026-07-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('undertakings', '0001_initial'), ('undertakings', '0002_rename_id_costcenter_identifier_and_more'), ('undertakings', '0003_rename_identifier_costcenter_id_and_more'), ('undertakings', '0004_undertaking_manager')]

    dependencies = [
        ('people', '0001_initial_squashed_0006_rename_identifier_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Undertaking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undertakings', to='undertakings.costcenter')),
                ('manager', models.ForeignKey(default='AP5788', on_delete=django.db.models.deletion.CASCADE, related_name='managed_undertakings', to='people.person')),
            ],
        ),
    ]
