# Generated by Django 5.1.2 on 2025-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("undertakings", "0002_rename_id_costcenter_identifier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costcenter",
            old_name="identifier",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="undertaking",
            old_name="identifier",
            new_name="id",
        ),
    ]
