# Generated by Django 5.1.2 on 2025-02-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_rename_identifier_person_id"),
        ("undertakings", "0003_rename_identifier_costcenter_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="undertaking",
            name="manager",
            field=models.ForeignKey(
                default="AP5788",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_undertakings",
                to="people.person",
            ),
            preserve_default=False,
        ),
    ]
