# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_person_description_alter_person_first_name_and_more'),
        ('undertakings', '0001_initial_squashed_0004_undertaking_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='id',
            field=models.IntegerField(help_text='Business-supplied cost-center identifier (integer, immutable).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(help_text='Display name of the cost center.', max_length=255),
        ),
        migrations.AlterField(
            model_name='undertaking',
            name='cost_center',
            field=models.ForeignKey(help_text='Cost center this undertaking rolls up to.', on_delete=django.db.models.deletion.CASCADE, related_name='undertakings', to='undertakings.costcenter'),
        ),
        migrations.AlterField(
            model_name='undertaking',
            name='id',
            field=models.IntegerField(help_text='Business-supplied undertaking identifier (integer, immutable).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='undertaking',
            name='manager',
            field=models.ForeignKey(help_text='Person accountable for this undertaking (the Undertaking Manager).', on_delete=django.db.models.deletion.CASCADE, related_name='managed_undertakings', to='people.person'),
        ),
        migrations.AlterField(
            model_name='undertaking',
            name='name',
            field=models.CharField(help_text='Display name of the undertaking (project / workstream).', max_length=255),
        ),
    ]
