"""Define the roles for the application."""

from rolepermissions.roles import AbstractUserRole


class Person(AbstractUserRole):
    """Person role."""

    available_permissions = {
        "view_person": True,
        "view_order": False,
        "view_company": False,
        "view_undertaking": False,
        "view_engagement": False,
        "view_engagement_order_version_assignment": False,
        "view_engagement_undertaking_assignment": False,
        "view_leave": True,
        "view_contract": False,
        "add_person": False,
        "change_person": False,
        "delete_person": False,
        "add_order": False,
        "change_order": False,
        "delete_order": False,
        "add_company": False,
        "change_company": False,
        "delete_company": False,
        "add_undertaking": False,
        "change_undertaking": False,
        "delete_undertaking": False,
        "add_engagement": False,
        "change_engagement": False,
        "delete_engagement": False,
        "add_engagement_order_version_assignment": False,
        "change_engagement_order_version_assignment": False,
        "delete_engagement_order_version_assignment": False,
        "add_engagement_undertaking_assignment": False,
        "change_engagement_undertaking_assignment": False,
        "delete_engagement_undertaking_assignment": False,
        "add_leave": True,
        "change_leave": True,
        "delete_leave": True,
        "add_contract": False,
        "change_contract": False,
        "delete_contract": False,
    }


class UndertakingManager(AbstractUserRole):
    """Undertaking Manager role."""

    available_permissions = {
        "view_person": True,
        "view_order": True,
        "view_company": True,
        "view_undertaking": True,
        "view_engagement": True,
        "view_engagement_order_version_assignment": True,
        "view_engagement_undertaking_assignment": True,
        "view_leave": True,
        "view_contract": True,
        "add_person": False,
        "change_person": False,
        "delete_person": False,
        "add_order": False,
        "change_order": False,
        "delete_order": False,
        "add_company": False,
        "change_company": False,
        "delete_company": False,
        "add_undertaking": True,
        "change_undertaking": True,
        "delete_undertaking": True,
        "add_engagement": False,
        "change_engagement": False,
        "delete_engagement": False,
        "add_engagement_order_version_assignment": False,
        "change_engagement_order_version_assignment": False,
        "delete_engagement_order_version_assignment": False,
        "add_engagement_undertaking_assignment": False,
        "change_engagement_undertaking_assignment": False,
        "delete_engagement_undertaking_assignment": False,
        "add_leave": False,
        "change_leave": False,
        "delete_leave": False,
        "add_contract": False,
        "change_contract": False,
        "delete_contract": False,
    }


class Admin(AbstractUserRole):
    """Admin role."""

    available_permissions = {
        "view_person": True,
        "view_order": True,
        "view_company": True,
        "view_undertaking": True,
        "view_engagement": True,
        "view_engagement_order_version_assignment": True,
        "view_engagement_undertaking_assignment": True,
        "view_leave": True,
        "view_contract": True,
        "add_person": True,
        "change_person": True,
        "delete_person": True,
        "add_order": True,
        "change_order": True,
        "delete_order": True,
        "add_company": True,
        "change_company": True,
        "delete_company": True,
        "add_undertaking": True,
        "change_undertaking": True,
        "delete_undertaking": True,
        "add_engagement": True,
        "change_engagement": True,
        "delete_engagement": True,
        "add_engagement_order_version_assignment": True,
        "change_engagement_order_version_assignment": True,
        "delete_engagement_order_version_assignment": True,
        "add_engagement_undertaking_assignment": True,
        "change_engagement_undertaking_assignment": True,
        "delete_engagement_undertaking_assignment": True,
        "add_leave": True,
        "change_leave": True,
        "delete_leave": True,
        "add_contract": True,
        "change_contract": True,
        "delete_contract": True,
    }
