# Generated by Django 5.1.15 on 2026-07-30 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('leaves', '0001_initial'), ('leaves', '0002_alter_leave_percentage')]

    dependencies = [
        ('people', '0001_initial_squashed_0006_rename_identifier_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='people.person')),
            ],
        ),
    ]
