# Generated by Django 5.1.2 on 2024-11-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_person_location_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='people.person')),
            ],
        ),
    ]
