# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial_squashed_0002_alter_leave_percentage'),
        ('people', '0009_alter_person_description_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(help_text='Inclusive last day of the leave.'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Share of the working day the person is on leave, in [0, 1]; 1.00 = full day off.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='person',
            field=models.ForeignKey(help_text='Person taking the leave.', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='people.person'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(help_text='Inclusive first day of the leave.'),
        ),
    ]
