# Generated by Django 5.1.15 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('companies', '0001_initial'), ('companies', '0002_rename_id_company_identifier'), ('companies', '0003_rename_identifier_company_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
