# Generated by Django 5.1.2 on 2025-02-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='identifier',
        ),
    ]
