# Generated by Django 5.1.2 on 2025-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_rename_id_company_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="identifier",
            new_name="id",
        ),
    ]
