# Generated by Django 5.1.15 on 2026-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial_squashed_0003_rename_identifier_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Primary billing / contact email for the company.', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.IntegerField(help_text='Business-supplied company identifier (integer, immutable).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text="Display name of the company (e.g. 'Acme Corp').", max_length=255),
        ),
    ]
