# Generated by Django 5.0.14 on 2025-06-14 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("people", "0001_initial"),
        ("people", "0002_person_description"),
        ("people", "0003_person_location_alter_person_id"),
        ("people", "0004_person_user"),
        ("people", "0005_rename_id_person_identifier"),
        ("people", "0006_rename_identifier_person_id"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
