# Generated by Django 5.1.2 on 2024-10-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
