# Generated by Django 5.1.2 on 2025-02-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_person_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="id",
            new_name="identifier",
        ),
    ]
