# Generated by Django 5.1.2 on 2025-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_rename_id_person_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="identifier",
            new_name="id",
        ),
    ]
