# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_description_alter_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Free-form note about the person (skills, role, etc.).'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Given name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(help_text="Six-character HR person identifier (e.g. 'P00042'). Immutable.", max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Family name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Primary work location (city or country).', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked Django auth user; NULL for people who cannot log in.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
