# Generated by Django 5.0.14 on 2025-06-14 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("orders", "0001_initial"),
        ("orders", "0002_remove_contract_order_orderversion_and_more"),
        ("orders", "0003_alter_orderversion_id_and_more"),
        ("orders", "0004_order_company"),
        ("orders", "0005_orderversion_end_date_orderversion_start_date"),
        ("orders", "0006_orderversion_contract_delete_contract"),
        ("orders", "0007_rename_id_order_identifier"),
        ("orders", "0008_rename_identifier_order_id"),
    ]

    dependencies = [
        ("companies", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        default=1234,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="orders.order",
                    ),
                ),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "contract",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_version",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "version_number")},
            },
        ),
    ]
