# Generated by Django 5.1.2 on 2024-10-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderVersion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='order_version',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='orders.orderversion'),
            preserve_default=False,
        ),
    ]
