# Generated by Django 5.1.2 on 2024-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_contract_order_orderversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='orderversion',
            unique_together={('order', 'version_number')},
        ),
    ]
