# Generated by Django 5.1.2 on 2024-10-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0003_alter_orderversion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company'),
            preserve_default=False,
        ),
    ]
