# Generated by Django 5.1.2 on 2024-12-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('orders', '0005_orderversion_end_date_orderversion_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderversion',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_version', to='contracts.contract'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
