# Generated by Django 5.1.2 on 2025-02-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderversion_contract_delete_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='identifier',
        ),
    ]
