# Generated by Django 5.1.2 on 2025-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_rename_id_order_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="identifier",
            new_name="id",
        ),
    ]
