# Generated by Django 5.0.14 on 2025-06-14 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_rename_identifier_company_id"),
        ("contracts", "0003_rename_identifier_contract_id"),
        ("orders", "0001_initial_squashed_0008_rename_identifier_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="orderversion",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_version",
                to="contracts.contract",
            ),
        ),
        migrations.AlterField(
            model_name="orderversion",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="orderversion",
            name="start_date",
            field=models.DateField(),
        ),
    ]
