# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_email_alter_company_id_and_more'),
        ('contracts', '0004_alter_contract_id_alter_contract_name_and_more'),
        ('orders', '0009_alter_order_company_alter_orderversion_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(help_text='The billing Company that owns this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(help_text='Business-supplied order identifier (integer, immutable).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Display name of the order.', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderversion',
            name='contract',
            field=models.OneToOneField(help_text='Contract underpinning this specific order version (1:1).', on_delete=django.db.models.deletion.CASCADE, related_name='order_version', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='orderversion',
            name='end_date',
            field=models.DateField(help_text='Inclusive last day this version is in effect.'),
        ),
        migrations.AlterField(
            model_name='orderversion',
            name='order',
            field=models.ForeignKey(help_text='Order this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderversion',
            name='start_date',
            field=models.DateField(help_text='Inclusive first day this version is in effect.'),
        ),
        migrations.AlterField(
            model_name='orderversion',
            name='version_number',
            field=models.IntegerField(help_text='Monotonically increasing version index within the order (1, 2, 3…).'),
        ),
    ]
