# Generated by Django 5.0.14 on 2025-06-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("engagements", "0001_initial"),
        ("engagements", "0002_alter_engagement_fte"),
        ("engagements", "0003_assignments"),
        ("engagements", "0004_rename_assignments_assignment"),
        ("engagements", "0005_alter_assignment_percentage_alter_engagement_fte"),
        ("engagements", "0006_alter_engagement_unique_together"),
        ("engagements", "0007_alter_assignment_unique_together"),
        (
            "engagements",
            "0008_alter_assignment_unique_together_assignment_end_date_and_more",
        ),
        (
            "engagements",
            "0009_alter_engagement_unique_together_alter_engagement_id_and_more",
        ),
        ("engagements", "0010_rename_id_engagement_identifier"),
        ("engagements", "0011_rename_identifier_engagement_id"),
    ]

    dependencies = [
        ("orders", "0004_order_company"),
        ("orders", "0005_orderversion_end_date_orderversion_start_date"),
        ("orders", "0006_orderversion_contract_delete_contract"),
        ("people", "0003_person_location_alter_person_id"),
        ("undertakings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Engagement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fte", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="EngagementOrderVersionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_version_assignments",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "order_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_assignments",
                        to="orders.orderversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("engagement", "order_version")},
            },
        ),
        migrations.CreateModel(
            name="EngagementUndertakingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="undertaking_assignments",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "undertaking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_assignments",
                        to="undertakings.undertaking",
                    ),
                ),
            ],
            options={
                "unique_together": {("engagement", "undertaking", "start_date")},
            },
        ),
    ]
