# Generated by Django 5.1.2 on 2024-10-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_company'),
        ('people', '0003_person_location_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='orders.orderversion')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='people.person')),
            ],
        ),
    ]
