# Generated by Django 5.1.2 on 2024-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='fte',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
