# Generated by Django 5.1.15 on 2026-08-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_rename_permission_codenames'),
        ('orders', '0010_alter_order_company_alter_order_id_alter_order_name_and_more'),
        ('people', '0009_alter_person_description_alter_person_first_name_and_more'),
        ('undertakings', '0005_alter_costcenter_id_alter_costcenter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='Cost per full working day in the engagement currency (before FTE weighting).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='end_date',
            field=models.DateField(help_text='Inclusive last day of the engagement.'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='fte',
            field=models.DecimalField(decimal_places=2, help_text='Full-time-equivalent factor in [0, 1]; 1.00 = full-time, 0.50 = half-time.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='person',
            field=models.ForeignKey(help_text='Person engaged (contractor or employee).', on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='people.person'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='start_date',
            field=models.DateField(help_text='Inclusive first day of the engagement.'),
        ),
        migrations.AlterField(
            model_name='engagementorderversionassignment',
            name='engagement',
            field=models.ForeignKey(help_text='Engagement being billed against the order version.', on_delete=django.db.models.deletion.CASCADE, related_name='order_version_assignments', to='engagements.engagement'),
        ),
        migrations.AlterField(
            model_name='engagementorderversionassignment',
            name='order_version',
            field=models.ForeignKey(help_text='Order version funding the engagement (all versions must share one Order).', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_assignments', to='orders.orderversion'),
        ),
        migrations.AlterField(
            model_name='engagementundertakingassignment',
            name='end_date',
            field=models.DateField(help_text='Inclusive last day of the allocation (must fall within the engagement).'),
        ),
        migrations.AlterField(
            model_name='engagementundertakingassignment',
            name='engagement',
            field=models.ForeignKey(help_text='Engagement whose time is being allocated.', on_delete=django.db.models.deletion.CASCADE, related_name='undertaking_assignments', to='engagements.engagement'),
        ),
        migrations.AlterField(
            model_name='engagementundertakingassignment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text="Share of the engagement's FTE spent on this undertaking, in [0, 1].", max_digits=3),
        ),
        migrations.AlterField(
            model_name='engagementundertakingassignment',
            name='start_date',
            field=models.DateField(help_text='Inclusive first day of the allocation (must fall within the engagement).'),
        ),
        migrations.AlterField(
            model_name='engagementundertakingassignment',
            name='undertaking',
            field=models.ForeignKey(help_text='Undertaking receiving the allocation.', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_assignments', to='undertakings.undertaking'),
        ),
    ]
