# Generated by Django 5.1.2 on 2024-10-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_alter_engagement_fte'),
        ('undertakings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='engagements.engagement')),
                ('undertaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='undertakings.undertaking')),
            ],
        ),
    ]
