# Generated by Django 5.1.2 on 2024-10-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_assignments'),
        ('undertakings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
    ]
