# Generated by Django 5.1.2 on 2024-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_rename_assignments_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='fte',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
