# Generated by Django 5.1.2 on 2024-11-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0005_alter_assignment_percentage_alter_engagement_fte'),
        ('orders', '0005_orderversion_end_date_orderversion_start_date'),
        ('people', '0003_person_location_alter_person_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('order_version', 'person')},
        ),
    ]
