# Generated by Django 5.1.2 on 2024-11-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_alter_engagement_unique_together'),
        ('undertakings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('engagement', 'undertaking')},
        ),
    ]
