# Generated by Django 5.1.2 on 2024-12-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0008_alter_assignment_unique_together_assignment_end_date_and_more'),
        ('orders', '0006_orderversion_contract_delete_contract'),
        ('people', '0003_person_location_alter_person_id'),
        ('undertakings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('person', 'start_date')},
        ),
        migrations.AlterField(
            model_name='engagement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EngagementOrderVersionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_version_assignments', to='engagements.engagement')),
                ('order_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_assignments', to='orders.orderversion')),
            ],
            options={
                'unique_together': {('engagement', 'order_version')},
            },
        ),
        migrations.CreateModel(
            name='EngagementUndertakingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undertaking_assignments', to='engagements.engagement')),
                ('undertaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_assignments', to='undertakings.undertaking')),
            ],
            options={
                'unique_together': {('engagement', 'undertaking', 'start_date')},
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='order_version',
        ),
    ]
