# Generated by Django 5.1.2 on 2025-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0010_rename_id_engagement_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engagement",
            old_name="identifier",
            new_name="id",
        ),
    ]
